config/routes.rb
RitlyApp::Application.routes.draw do
  
  root to: 'site#index'

  get '/links', to: 'links#index', as: :links

  get '/links/new', to: 'links#new', as: :new_link

  post '/links', to: 'links#create'

  get '/links/:id', to: 'links#show', as: :link

  get 'links/:id/delete', to: 'links#delete'

  get '/go/:code/preview', to: 'links#preview', as: :preview

  get '/go/:code', to: 'links#go', as: :go

end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
  	@links = Link.all
  end

  def new
  	@link = Link.new
  end

  def create
  	new_params = {}
    input_params = params.require(:link).permit(:input_link)
    new_params[:input_link] = input_params[:input_link]
    new_params[:output_code] = SecureRandom.urlsafe_base64(6)
    link = Link.create(new_params)
    redirect_to link_path(link.id)
  end

  def show
    id = params[:id]
    @link = Link.find(id)
  end

  def preview
    current_code = params[:code]
  	current_record = Link.find_by output_code: current_code
    current_id = current_record.id
    redirect_to link_path(current_id)
  end

  def go
  	current_code = params[:code]
  	current_record = Link.find_by output_code: current_code
    destination = current_record.input_link
    redirect_to destination
  end

  def delete
    id = params[:id]
    deleted_link = Link.find(id)
    deleted_link.destroy
    redirect_to links_path
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Ritly</title>

        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
          <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
          <%= csrf_meta_tags %>
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">


    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand" href="#">Project name</a> -->
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/links/new">Shorten Link</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
            <br>
            <br>
            <br>
            <br>

                  <%= yield %>

    </div><!-- /.container -->

  



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/links/index.html.erb
<h3>List of Links and Codes</h3></br>

<table class="table table-hover">

<tr>
  <th>ID</th>
  <th>Input Link</th>
  <th>Output Code</th>

  <th>Created</th>
  <th>Updated</th>
</tr>

<% @links.each do |link| %>

<tr>
  <td><%= link.id %></td>
  <td><a href="<%= link.input_link %>"><%= link.input_link %></a></td>

  <td><a href="/go/<%= link.output_code %>/"><%= link.output_code %></a></td>
  <td><%= link.created_at %></td>

  <td><%= link.updated_at%></td>
  <td><a href="/links/<%= link.id %>/delete"><button class="delete">Delete</button></a></td>
</tr>

<% end %>

</table>

app/views/links/new.html.erb
<div>

Enter URL to be shortened. Be sure to enter the starting 'http://' :
</br>
</br>

<%= form_for @link do |f| %>
    <%= f.text_field :input_link, placeholder: "enter URL" %> <br></br>
    
    <%= f.submit %>
<% end %>

</div>

app/views/links/show.html.erb
<div>

<p>You entered <%= @link.input_link %>.</p>

<p>Your Ritly shortened URL code is <%= @link.output_code %>.</p>

<p>Go to <a href="/go/<%= @link.output_code %>">localhost:3000/go/<%= @link.output_code %></a> to visit your URL.</p>

</div>

app/views/site/index.html.erb
<h1> Welcome to Ritly! </h1>

<p><%= link_to "Shorten a link with Ritly", new_link_path %></p>